### ISSUE TITLE
Movies instead TV Shows in README

### ISSUE THREAD

**Issue by sergiocos** [TheChrisK/PMM#13]
Not a big one, but confused me a little. You have Movies instead TV Shows in your README, as you can see in the pic
![movie-tv](https://github.com/TheChrisK/PMM/assets/324188/e8b1331c-667a-4bec-a20a-670f03d63a20)

Thanks for the config, the TV Show Network and Status is amazing. Cheers

**Comment by TheChrisK** [comment]
> Not a big one, but confused me a little. You have Movies instead TV Shows in your README, as you can see in the pic ![movie-tv](https://private-user-images.githubusercontent.com/324188/346277999-e8b1331c-667a-4bec-a20a-670f03d63a20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTQzODIsIm5iZiI6MTcyMDI5NDA4MiwicGF0aCI6Ii8zMjQxODgvMzQ2Mjc3OTk5LWU4YjEzMzFjLTY2N2EtNGJlYy1hMjBhLTY3MGYwM2Q2M2EyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxOTI4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTUyMTVjMDBiYmMxMTBhMjgzMzgwZjlmNDdjZDgxYzQyNjBjNDQ3MDRhNzAyYjYwNzJiNWM5OTY5ZjZiMWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ItensSdmi0lf99w_jq8twFjgaSsHwiUmr01qipsl5-E)
> 
> Thanks for the config, the TV Show Network and Status is amazing. Cheers

Thank you!
