### ISSUE TITLE
No overlay for tv show status, only for network

### ISSUE THREAD

**Issue by sergiocos** [TheChrisK/PMM#17]
For few days now my newly added tv shows won't get the overlay for status, only the network overlay. Might have to do with the TMDB date change?
https://www.reddit.com/r/Kometa/comments/1h8erel/tmdb_date_change_issue/

**Comment by TheChrisK** [comment]
You are correct. It is due to the date change in the TMDB API.

The workaround will have to do until a new build is pushed. It is detailed in the Kometa Discord.

**Comment by sergiocos** [comment]
Works great again, after the update of tmdbapis. Thanks again for your work! Cheers!

**Comment by TheChrisK** [comment]
> Works great again, after the update of tmdbapis. Thanks again for your work! Cheers!

TMDB have identified and will fix the issue. Expect the workaround to break things again and when that happens, you can remove the file mapping workaround.
