### ISSUE TITLE
PMM setting custom overlays to tv shows but not movies

### ISSUE THREAD

**Issue by lizar93** [TheChrisK/PMM#2]
As the title says, i´ve used your code for the custom overlays. The tv shows worked from the beggining, but movies don´t. I´m stuck with de pmm default resolution overlay, not your custom top left with the audio codec etc.

I think i have the config file well aligned and no typos. PMM detects the movies but looks like it fails retrieving the github urls. I´ll attatch the log, the config file and some screenshots 
This is the first time posting on github so let me know if something is missing.

[config.txt](https://github.com/TheChrisK/PMM/files/15048423/config.txt)
![default_movie_overlays](https://github.com/TheChrisK/PMM/assets/35570035/19941de4-ef8d-4035-b34d-926a3cbeb08e)
![TV_overlays_working](https://github.com/TheChrisK/PMM/assets/35570035/42ffedd8-338f-42fc-8f86-d42f5d26b261)

[meta.log](https://github.com/TheChrisK/PMM/files/15048424/meta.log)

**Comment by TheChrisK** [comment]
Try running your config using the [-ov](https://metamanager.wiki/en/latest/pmm/environmental/#overlays-only) and [-is](https://metamanager.wiki/en/latest/pmm/environmental/#ignore-schedules) flags. This will run overlays only and ignore schedules.

Only one overlay gave a 404 error due to special characters.

The config has them running between 6am and 7am. I probably need to change that or make it clearer.

**Comment by lizar93** [comment]
you mean python plex_meta_manager.py -ov -is --run?

**Comment by TheChrisK** [comment]
Interesting. It sort of worked but your log says it can't find some of the ribbons. I copied the URLs and checked and they are all accessible. 

Can you access [this image](https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/background-top-left/top-left-313-wide.png) from your network?

**Comment by lizar93** [comment]
Yes, tried from my phone and I see the black corner background

**Comment by TheChrisK** [comment]
I have to run. I'll be back on later to help. 

In the mean time, can you switch to the develop branch of PMM and try again?

**Comment by lizar93** [comment]
Sure, I'll try thx!!

**Comment by TheChrisK** [comment]
I was able to replicate this in my dev environment. Same issues but I found the issue. I erroneously had the overlay images in the configs set as `file:` instead of `url:`. I have updated them and pushed it out. Please give it another go, you shouldn't need to change anything.

**Comment by lizar93** [comment]
i just run it and same...i´ll link again the config and log but before this i installed fresh (deleted the pmm app data) and the codecs still were there. I must have the metadata somewhere, maybe thats the problem?

[config.txt](https://github.com/TheChrisK/PMM/files/15049363/config.txt)

[meta.log](https://github.com/TheChrisK/PMM/files/15049364/meta.log)

**Comment by TheChrisK** [comment]
It will if you change

'use_1080p: false'

to

'use_1080p: true' 

Or just remove that line altogether. I currently only use it for 4K.

Thank you for your patience. I'm glad it's working now. I kind of rushed sharing this out and it shows.

**Comment by lizar93** [comment]
ooohhh yes i see (too worried and didnt pay attention to =false. Once it finishes ill add the post credits scene and run it again because when overlaying Hobbit files i read some ssl error or exception.

I should be the one thanking you :)

**Comment by TheChrisK** [comment]
> ooohhh yes i see (too worried and didnt pay attention to =false. Once it finishes ill add the post credits scene and run it again because when overlaying Hobbit files i read some ssl error or exception.
> 
> I should be the one thanking you :)

Let me know if anything else comes up. Your role as Guinea Pig will be honored. :)
