### ISSUE TITLE
Adjusting overlay size

### ISSUE THREAD

**Issue by lizar93** [TheChrisK/PMM#3]
hi, its me again!
just one simple question. i finally removed the audio codec as it isnt relevan to me. Therefore the resolution overlay feels too small, i tried adjusting back_width and back_height but it appears to do nothing. is it posible to adjust the "4k hdr", "1080" overlay size? or its just an image and cant resize it? Also it sits on the bottom of the black background (as intended for you because yo also have audio codec and both fit perferctly), can i center it?

**Comment by TheChrisK** [comment]
Since these were designed to work together with the background, a redesign/resizing would be needed for proper center fit.
