### ISSUE TITLE
Where is the pmm metadata located

### ISSUE THREAD

**Issue by lizar93** [TheChrisK/PMM#4]
I was wondering where all codec, background etc metadata is located. Now that for example I don't use audio codec overlay, I would like to remove them from my drive.

I'm looking at my Plex metadata folder but not sure where to look at

**Comment by lizar93** [comment]
yeah ive come across that but cant get it working so i was wondering if there was a different method. i assume deleting the whole metadata folder isnt an option (also its like 90+ gb)

**Comment by TheChrisK** [comment]
Yeah don't delete that folder. Plex Image Cleanup is the best way. The git repo has instructions as well to just run the script without standing up a docker container.
